### ISSUE TITLE
very old navmesh gen lib

### ISSUE THREAD

**Issue by bmorel** [DaemonEngine/daemonmap#5]
There were lot of bugfixes those last 4 years in recastnavigation. Those fixes improves a lot the situation concerning the flickering navedit. I'm not sure if they improve more than that, though.

**Comment by illwieckz** [comment]
Would be good to have anyway!

**Comment by bmorel** [comment]
The only thing preventing simple merging is that the lib fails to build in debug mode, because of some custom assert stuff not being implemented. The solution is rather easy: to redefine dtAssert() and ctAssert() or something like that as just "assert", but that imply patching the submodule, and I'm not fond of that idea.
Ideally, something less intrusive should be made, but that lib is rather badly documented imo, so it will waste more time to do that.

**Comment by illwieckz** [comment]
@slipher would you be able to do this update? That would probably be something similar to https://github.com/DaemonEngine/Daemon/commit/a7d235e74fe6559049c8b89f46f9eb803e931123

**Comment by bmorel** [comment]
I got it to build by hacking directly recast's source code, but that's not pretty and means maintaining a patch over it, and nobody really have time for that.

**Comment by slipher** [comment]
It was fixed by #6.
