### ISSUE TITLE
lighting bug making some surfaces invisible

### ISSUE THREAD

**Issue by necessarily-equal** [DaemonEngine/daemonmap#8]
On a test map I made, I managed to break the lighting by making a large ceiling with a light texture (not very bright, of luminosity 200).

An example of a broken platform:
![Screenshot from 2021-11-21 22-34-57](https://user-images.githubusercontent.com/59283660/142779802-a46dbc49-309e-472a-801f-25d60489f15d.png)

An example of non-broken platform (on other side):
![Screenshot from 2021-11-21 22-34-47](https://user-images.githubusercontent.com/59283660/142779807-1801bbfb-0e35-4865-87c4-4f62d7c54757.png)

For looking at it quickly, I didn't notice a pattern of why some platforms become transparent, and why others don't.

Test map attached: [map.zip](https://github.com/DaemonEngine/daemonmap/files/7577161/map.zip)

**Comment by slipher** [comment]
This repo is only about navmesh generation. The living q3map2 is in https://gitlab.com/xonotic/netradiant

**Comment by necessarily-equal** [comment]
https://gitlab.com/xonotic/netradiant/-/issues/160
